### ISSUE TITLE
Clause using Enumerator::comitClause is ignored

### ISSUE THREAD

**Issue by rkaminsk** [potassco/clasp#74] opened 2022-02-27 11:55 UTC
The example below (using the Clingo API) triggers a bug when committing a clause. It seems like a committed clause is ignored. There seems to be (at least) three ways to work around the problem:
- disable equivalence preprocessing
- do not introduce atoms that create the trivial equivalences
- readd the clause after every model

The example and it's grounding is luckily quite small:
```c++
#include <clingo.hh>

int main() {
    // using
    //auto ctl = Clingo::Control{{"--eq", "0"}};
    // instead of
    auto ctl = Clingo::Control{};
    // makes the example work
    ctl.add("base", {}, R"(
pigeon(3). hole(4).

pigeon(X-1) :- pigeon(X), X > 1.
hole(X-1) :- hole(X), X > 1.

{assign(P,H) : hole(H)} = 1 :- pigeon(P).
:- assign(P1,H), assign(P2,H), P1 != P2.

% commenting out this line makes the example work
__opt(1,P,H) :- assign(P,H).)");
    ctl.ground({{"base", {}}});
    auto cfg = ctl.configuration();
    auto cfg_solve = cfg["solve"];
    auto cfg_solver = cfg["solver"];
    cfg_solve["models"] = "1";
    cfg_solver["rand_freq"] = "0.5";
    cfg_solver["seed"] = "2";
    cfg_solver["sign_def"] = "rnd";

    cfg_solve["models"] = "0";
    cfg_solver["seed"] = "23";

    auto syms = ctl.symbolic_atoms();
    std::vector<Clingo::literal_t> first;
    {
        auto hnd = ctl.solve();
        for (auto &&m : hnd) {
            std::cerr << "randomly picked solution to discard:" << std::endl;
            std::cerr << "  " << m << std::endl;
            for (auto &&sym : m.symbols(Clingo::ShowType::Atoms)) {
                first.emplace_back(-syms[sym].literal());
            }
            break;
        }
        hnd.get();
    }
    size_t n = 0;
    {
        auto hnd = ctl.solve();
        for (auto &&m : hnd) {
            ++n;
            if (n == 1) {
                // unconditionally adding this clause makes the example work
                m.context().add_clause(Clingo::LiteralSpan{first});
            }
            if (n > 1) {
                std::vector<Clingo::literal_t> other;
                for (auto &&sym : m.symbols(Clingo::ShowType::Atoms)) {
                    other.emplace_back(-syms[sym].literal());
                }
                if (other == first) {
                    std::cerr << "this solutions should not have been enumerated again:" << std::endl;
                    std::cerr << "  " << m << std::endl;
                }
            }
        }
        hnd.get();
    }
    std::cerr << "found " << n << " of 24 solutions" << std::endl;
}
```

**Comment by BenKaufmann** [comment] 2022-03-04 18:35
@rkaminsk The problem is that your code violates an (implicit) assumption of `Clasp::Enumerator::commitClause()`, namely that the clause passed to it does not contain duplicate and/or complementary literals.
The clause passed is: `[ 0 0 0 0 0 0 0 -2 -7 -12 -2 -7 -12 -16 ]` and once this is simplified to `[ 0 -2 -7 -12 -16 ]`, the program no longer prints the duplicated solution.

**Comment by rkaminsk** [comment] 2022-03-04 19:21
> @rkaminsk The problem is that your code violates an (implicit) assumption of `Clasp::Enumerator::commitClause()`, namely that the clause passed to it does not contain duplicate and/or complementary literals. The clause passed is: `[ 0 0 0 0 0 0 0 -2 -7 -12 -2 -7 -12 -16 ]` and once this is simplified to `[ 0 -2 -7 -12 -16 ]`, the program no longer prints the duplicated solution.

So a simple sort/unique should fix the problem?

**Comment by BenKaufmann** [comment] 2022-03-04 19:34
> So a simple sort/unique should fix the problem?

Plus adjacent_find to weed out tautologies.

> Are there any further conditions to consider?

Can't think of any atm.

**Comment by rkaminsk** [comment] 2022-03-04 19:41
I also filter the tautologies now. A pity that we cannot use the `ClauseCreator` here because, if I remember correctly, it knows how to do all these things.

**Comment by BenKaufmann** [comment] 2022-03-05 09:44
> A pity that we cannot use the ClauseCreator here because, if I remember correctly, it knows how to do all these things.

Agreed. But `ClauseCreator` needs a (modifiable) `Solver` in order to do simplifications, which we don't have at this point. While one could postpone any simplifications until clause integration time, this would create unnecessary (duplicate) work in the MT scenario and would also complicate the interface of "shared clause queue".

However, I could add a (static) `ClauseCreator::canonicalize(LitVec& clauseLits) -> Status` function that could _clausify_ the given `clauseLits` and return a status wrt the empty assignment (one of `status_empty`, `status_subsumed`, `status_unit`, or `status_open`). 

With such a function, `ClingoModel::addClause()` could then become:
```cpp
void addClause(Potassco::LitSpan const &lits) const override {
  Clasp::LitVec claspLits;
  for (const auto &x : lits) { claspLits.push_back(lp().getLiteral(x)); }
  claspLits.push_back(~ctx().stepLiteral());
  if (Clasp::ClauseCreator::canonicalize(claspLits) != Clasp::ClauseCreator::status_subsumed)
    model_->ctx->commitClause(claspLits);
}
```
Would you prefer that?

**Comment by rkaminsk** [comment] 2022-03-05 09:54
I am not sure but I might be the only user of the clasp interface. So I think it is not really necessary.

**Comment by BenKaufmann** [comment] 2022-03-05 12:02
Ok, I close this issue then.

**Closed by BenKaufmann** 2022-03-05 12:02 UTC
